### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sorairo580** [sorairo580/protospace-39405#1]
# URL
https://protospace-39405.onrender.com/

**Comment by shodai-ito** [comment]
@sorairo580 さん、ご提出ありがとうございます‼︎
動作確認を試みましたが、basic認証が導入されており、ページにアクセスできませんでした。
protospaceではbasic認証の導入は必須ではないため、一旦解除いただくかIDとパスワードの記載をお願いいたします。

どちらかの対応が完了しましたら、以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sorairo580** [comment]
ご確認ありがとうございます！

BASIC認証を解除（該当箇所をコメントアウト）を行いました。
誤ってISSUE2を作成してしまいました、申し訳ありません。
再度ご確認をお願い致します。
