### ISSUE TITLE
2【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sorairo580** [sorairo580/protospace-39405#2]
# URL
https://protospace-39405.onrender.com/

BASIC認証を解除しました。
ご確認ください。

**Comment by snkw-works** [comment]
@sorairo580 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
